chore: add small changes to Makefile

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -30,6 +30,21 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Prerequisites
+      run: |
+        if [[ "${{ inputs.is_org }}" == 'true' ]]; then
+          if [[ -z "${{ inputs.org }}" ]] || [[ "${{ inputs.org }}" == "" ]]; then
+            echo "Organization is required when is_org is true"
+            exit 1
+          fi
+        else:
+          if [[ -z "${{ inputs.gh_actor }}" ]] || [[ "${{ inputs.gh_actor }}" == "" ]]; then
+            echo "GitHub Actor is required when is_org is false"
+            exit 1
+          fi
+        fi
+      shell: bash
+
     - uses: actions/setup-python@v5
       with:
         python-version: '3.12'
@@ -47,6 +62,22 @@ runs:
       run: |
         echo "repo_name=$(echo "${{ inputs.repo }}" | rev | cut -d'/' -f1 | rev)" >> $GITHUB_OUTPUT
       shell: bash
+
+    - uses: actions/checkout@v4
+      if: ${{ inputs.is_org }} == 'true'
+      with:
+        repository: ${{ inputs.org }}/${{ steps.rname.outputs.repo_name }}
+        path: ${{ github.workspace }}/${{ inputs.org }}/${{ steps.rname.outputs.repo_name }}
+        fetch-depth: 0 # Fetch all history for all tags and branches
+        token: ${{ inputs.gh-token }}
+
+    - uses: actions/checkout@v4
+      if: ${{ inputs.is_org }} == 'false'
+      with:
+        repository: ${{ inputs.gh_actor }}/${{ steps.rname.outputs.repo_name }}
+        path: ${{ github.workspace }}/${{ inputs.gh_actor }}/${{ steps.rname.outputs.repo_name }}
+        fetch-depth: 0 # Fetch all history for all tags and branches
+        token: ${{ inputs.gh-token }}  
 
     - name: Sync Action Status
       env:
